---

- hosts: localhost

  tasks:
    - name: Pause for 60 seconds before start
      ansible.builtin.pause:
        seconds: 60

    - name: create external port for router
      os_port:
        state: present
        name: "{{ prefix }}_{{ router.name }}_ext_ip"
        network: "{{ router.ext_net }}"
        fixed_ips:
          - ip_address: "{{ router.ext_ip }}"
    - name: create internal  ports for router
      os_port:
        state: present
        name: "{{ item.port }}"
        network: "{{ prefix }}_{{ item.name }}_net"
        fixed_ips:
          - ip_address: "{{ item.ip }}"
      with_items: "{{ router.networks }}" 

    - name: Create router instance
      os_server:
        state: present
        name: "{{ prefix }}_{{ router.name }}"
        auto_ip: no
        image: "debian11_0"
        flavor: "—Å1m512d0"
        key_name: cloud
        boot_from_volume: True
        volume_size: "16"
        terminate_volume: yes
        nics:
          - port-name: "{{ prefix }}_{{ router.name }}_ext_ip"
          - port-name: "{{ prefix }}_personal_{{ router.name }}_ip"
          - port-name: "{{ prefix }}_disp_{{ router.name }}_ip"
          - port-name: "{{ prefix }}_ps_{{ router.name }}_ip"
        meta:
          hw_qemu_guest_agent: "yes"

    - name: openstack source
      shell: "source /awx_temp/awx-openrc.sh"

    - name: remove security group for router external port
      shell: "source /awx_temp/awx-openrc.sh && openstack port set --no-security-group {{ prefix }}_{{ router.name }}_ext_ip"
       
    - name: remove security group for router ports
      shell: "source /awx_temp/awx-openrc.sh && openstack port set --no-security-group {{ prefix }}_personal_{{ router.name }}_ip"

    - name: remove security group for router ports
      shell: "source /awx_temp/awx-openrc.sh && openstack port set --no-security-group {{ prefix }}_disp_{{ router.name }}_ip"

    - name: remove security group for router ports
      shell: "source /awx_temp/awx-openrc.sh && openstack port set --no-security-group {{ prefix }}_ps_{{ router.name }}_ip"

    - name: disable port-security for router external port
      shell: "source /awx_temp/awx-openrc.sh && openstack port set --disable-port-security {{ prefix }}_{{ router.name }}_ext_ip"
       
    - name: disable port-security for router ports
      shell: "source /awx_temp/awx-openrc.sh && openstack port set --disable-port-security {{ prefix }}_personal_{{ router.name }}_ip"

    - name: disable port-security for router ports
      shell: "source /awx_temp/awx-openrc.sh && openstack port set --disable-port-security {{ prefix }}_disp_{{ router.name }}_ip"

    - name: disable port-security for router ports
      shell: "source /awx_temp/awx-openrc.sh && openstack port set --disable-port-security {{ prefix }}_ps_{{ router.name }}_ip"
