---
- name: Install and Update
  hosts: all
  become: yes

  vars:
    src_folder: ./web
    src_file_folder: ./web/files
    dst_folder: /var/www/html

  tasks:
    #Ubuntu
    - block:
        - name: Install Apache for Ubuntu
          apt: name=apache2 state=latest
        - name: Start service Ubuntu
          service: name=apache2 state=started enabled=yes
      when: ansible_facts['os_family'] == "Debian"
    #RedHat
    - block:
        - name: Install Apache for RedHat
          yum: name=httpd state=latest
        - name: Start service RedHat
          service: name=httpd state=started enabled=yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Generate index.html
      template: src={{ src_folder }}/index.j2 dest={{ dst_folder }}/index.html mode=0555
      notify:
        - Restart Apache Ubuntu
        - Restart Apache RedHat

    - name: Copy file to webserver
      copy: src={{ item }} dest={{ dst_folder }} mode=0555
      loop: "{{ lookup('fileglob', '{{ src_file_folder }}/*', wantlist=True) }}"
      notify:
        - Restart Apache Ubuntu
        - Restart Apache RedHat

  handlers:
    - name: Restart Apache Ubuntu
      service: name=apache2 state=restarted
      when: ansible_facts['os_family'] == "Debian"

    - name: Restart Apache RedHat
      service: name=httpd state=restarted
      when: ansible_facts['os_family'] == "RedHat"
