---
- hosts: localhost
  gather_facts: no


  tasks:

  - name: Create network interface
    os_port:
      name              : "{{prefix}}_{{os_hostname}}_ip"
      state             : "{{state}}"
      network           : "{{prefix}}_{{os_networkname}}_net"
      fixed_ips: 
      - ip_address      : "10.{{s_oct}}.{{ip_ident}}"

  - name: Create instance
    os_server:
      name              : "{{prefix}}_{{os_hostname}}"
      state             : "{{state}}"
      key_name          : cloud
      nics              : 
        - port-name     : "{{prefix}}_{{os_hostname}}_ip"
      image             : "{{ image }}"
      flavor            : "{{ flavor }}"
      auto_floating_ip  : no
      boot_from_volume  : yes
      terminate_volume  : yes
      volume_size       : "{{ volume_size }}"
      timeout: 600
      meta :
        admin_pass          : "{{password}}"
        hw_qemu_guest_agent : "yes"
        local_hostname: "{{prefix}}_{{os_hostname}}"